### ISSUE TITLE
Application crash

### ISSUE THREAD

**Issue by umbros** [italia/spid-testenv-backoffice#3]
When I call a identity server api from backoffice, the application crash:
/spid-testenvironment/bo/backoffice/server/wso2/service-provider.js:342
					if(result.getRoleListOfUserResponse!=null) {
					         ^

TypeError: Cannot read property 'getRoleListOfUserResponse' of undefined
    at /spid-testenvironment/bo/backoffice/server/wso2/service-provider.js:342:15
    at /spid-testenvironment/bo/backoffice/node_modules/soap/lib/client.js:182:7
    at /spid-testenvironment/bo/backoffice/node_modules/soap/lib/client.js:353:7
    at Request._callback (/spid-testenvironment/bo/backoffice/node_modules/soap/lib/http.js:114:14)
    at self.callback (/spid-testenvironment/bo/backoffice/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/spid-testenvironment/bo/backoffice/node_modules/request/request.js:878:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

npm ERR! Linux 4.10.0-35-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "start-prod"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! react-frontend-converted@0.1.0 start-prod: `node server/spid-idp-backoffice.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-frontend-converted@0.1.0 start-prod script 'node server/spid-idp-backoffice.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-frontend-converted package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server/spid-idp-backoffice.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-frontend-converted
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-frontend-converted
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /spid-testenvironment/bo/backoffice/npm-debug.log

**Comment by damikael** [comment]
Fixed with latest changes on docker configuration
